---
# vars file for ./roles/install_aap
access_token_endpoint: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
grant_type: "refresh_token"
client_id: "rhsm-api"

retries: 15
delay: 60