---
# tasks file for ./roles/configure_aap
- name: Configure Image Builder
  when: config_imagebuilder | default(true)
  ansible.builtin.include_role:
    name: rprakashg.vpac.setup_imagebuilder

- name: Configure gitea
  become: true
  when: config_gitea | default(true)
  ansible.builtin.import_tasks: configure_gitea.yml

- name: Configure Influx
  when: config_influxdb | default(true)
  ansible.builtin.import_tasks: configure_influxdb.yml
  
- name: Configure aap
  when: config_aap | default(true)
  ansible.builtin.import_tasks: configure_aap.yml

  