---
# defaults file for ./roles/install_aap
aap_sha: 47197c8e2f909c3f5acc445d955d7ed8182dfb05b466c136ec24aedee8dce63e

eda_image: 'eda-controller-rhel9:latest'

node_fqdn: ''
install_aap: true

install_gitea: true
gitea_port: 3030
gitea_image: docker.io/gitea/gitea:latest

install_influxdb: true
influx_version: 2.7.5

install_loki: true
install_grafana: true