---
# vars file for ./roles/deploy_otelcollector
collector_download_url: "https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.124.1/otelcol-contrib_0.124.1_linux_386.tar.gz"