---
# defaults file for ./roles/deploy_ssc600sw
ssc600_vm:
  name: ssc600-1
  path: /vms/ssc600-1
  core0: 15
  core1: 14
  core2: 13
  core3: 12
  core_qemu: 16-17
  pb_nic: "{{ networking.processbus.nic }}"

ptp:
  status_dir: /home/libvirt-local/ptp/

ssc600_bundle:
  path: /home/software
  extracted_path: /home/software/abb