---
# tasks file for ./roles/create_windows_vm
- name: Preflight
  become: yes
  ansible.builtin.import_tasks: preflight.yml

- name: Create autounattend iso
  become: yes
  ansible.builtin.import_tasks: create_autounattend_iso.yml

#- name: Create a custom iso with auto unattend answer file
#  become: yes
#  ansible.builtin.import_tasks: create_custom_iso.yml

- name: Download virtio win drivers
  become: yes
  ansible.builtin.import_tasks: download_virtio_win_iso.yml
  
- name: Create windows virtual machine
  become: yes
  ansible.builtin.import_tasks: create_vm.yml
