---
# This task reboots the host and waits for it to be up
- name: Reboot host machine
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 1800
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime

- name: Pinging the host
  ansible.builtin.ping:

- name: "Print"
  ansible.builtin.debug:
    msg: "Finished rebooting host machine"
