---
# This example playbook enables virtualization on target RHEL host
- name: Enable virtualization playbook
  hosts: all
  gather_facts: yes
  tasks:
  - name: Enable virtualization
    ansible.builtin.import_role:
      name: prepare_system_for_rt